import url1 from '../musicbucket/musiccolAlbums/music1.mp3'
export const PopularTrackDataBase = [
    {
      id: 0,
      srno: 1,
      artist: 'Eminem',
      title: 'The Marshall Mathers LP',
      genre: 'Hip Hop',
      duration: '6:44',
      url: url1,
      cover: 'https://res.cloudinary.com/djcyhbk2e/image/upload/c_fit,f_auto,h_800,q_35,w_800/v1/gvv/prod/mrzwba5gulxk2y3eflsx',
      description: 'The Marshall Mathers LP is the third studio album by Eminem.',
      link: 'https://example.com/mmlp',
      songs: [
        { id: 101, title: 'Stan', duration: '6:44' },
        { id: 102, title: 'The Real Slim Shady', duration: '4:44' },
      ],
    },
    {
      id: 1,
      srno: 2,
      artist: 'Adele',
      album: '21',
      duration: '6:44',
      url: url1,
      genre: 'Pop',
      cover: 'https://res.cloudinary.com/djcyhbk2e/image/upload/c_fit,f_auto,h_800,q_35,w_800/v1/gvv/prod/mrzwba5gulxk2y3eflsx',
      description: '21 is the second studio album by Adele, released in 2011.',
      link: 'https://example.com/21',
      songs: [
        { id: 201, title: 'Rolling in the Deep', duration: '3:48' },
        { id: 202, title: 'Someone Like You', duration: '4:45' },
      ],
    },
    {
      id: 2,
      srno: 3,
      artist: 'Kanye West',
      duration: '6:44',
      url: url1,
      album: 'My Beautiful Dark Twisted Fantasy',
      genre: 'Rap',
      cover: 'https://res.cloudinary.com/djcyhbk2e/image/upload/c_fit,f_auto,h_800,q_35,w_800/v1/gvv/prod/mrzwba5gulxk2y3eflsx',
      description: 'My Beautiful Dark Twisted Fantasy is the fifth studio album by Kanye West.',
      link: 'https://example.com/mbdtf',
      songs: [
        { id: 301, title: 'Power', duration: '4:52' },
        { id: 302, title: 'Runaway', duration: '9:08' },
      ],
    },
    {
      id: 3,
      srno: 4,
      artist: 'Taylor Swift',
      album: '1989',
      genre: 'Pop',
      url: url1,
      duration: '6:44',
      cover: 'https://res.cloudinary.com/djcyhbk2e/image/upload/c_fit,f_auto,h_800,q_35,w_800/v1/gvv/prod/mrzwba5gulxk2y3eflsx',
      description: '1989 is the fifth studio album by Taylor Swift, released in 2014.',
      link: 'https://example.com/1989',
      songs: [
        { id: 401, title: 'Shake It Off', duration: '3:39' },
        { id: 402, title: 'Blank Space', duration: '3:51' },
      ],
    },
    {
      id: 4,
      srno: 5,
      artist: 'Drake',
      album: 'Views',
      duration: '6:44',
      url: url1,
      genre: 'Hip Hop',
      cover: 'https://res.cloudinary.com/djcyhbk2e/image/upload/c_fit,f_auto,h_800,q_35,w_800/v1/gvv/prod/mrzwba5gulxk2y3eflsx',
      description: 'Views is the fourth studio album by Drake, released in 2016.',
      link: 'https://example.com/views',
      songs: [
        { id: 501, title: 'Hotline Bling', duration: '4:27' },
        { id: 502, title: 'One Dance', duration: '2:54' },
      ],
    },
    // Add more diverse albums as needed
  ];
  